package main

import (
 "crypto/rand"
 "crypto/sha256"
 "encoding/hex"
 "encoding/json"
 "fmt"
 "net/http"
 "strings"
 "time"

 "golang.org/x/crypto/bcrypt"
)

func userPortalToken(r *http.Request) string { if c,err:=r.Cookie("lumo_session"); err==nil { return strings.TrimSpace(c.Value) }; return strings.TrimSpace(r.Header.Get("Authorization")) }
func hashPortalToken(v string) string { b:=sha256.Sum256([]byte(v)); return hex.EncodeToString(b[:]) }
func newPortalToken() (string,error) { b:=make([]byte,32); if _,err:=rand.Read(b);err!=nil{return "",err};return hex.EncodeToString(b),nil }
func newPublicCode(prefix string,n int)(string,error){for i:=0;i<20;i++{b:=make([]byte,n);if _,err:=rand.Read(b);err!=nil{return "",err};code:=strings.ToUpper(hex.EncodeToString(b));if prefix!=""{code=prefix+code};var exists bool;if err:=userDB.QueryRow(`SELECT EXISTS(SELECT 1 FROM public.app_users WHERE user_id=$1 OR referral_code=$1)`,code).Scan(&exists);err!=nil{return "",err};if !exists{return code,nil}};return "",fmt.Errorf("could not generate unique code")}
func portalUser(r *http.Request)(string,bool){token:=userPortalToken(r);if token==""{return "",false};var id string;err:=userDB.QueryRow(`SELECT u.user_id FROM public.user_sessions_auth s JOIN public.app_users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND u.status='active'`,hashPortalToken(token)).Scan(&id);return id,err==nil}
func userJSON(w http.ResponseWriter,v any){w.Header().Set("Content-Type","application/json");_=json.NewEncoder(w).Encode(v)}
func userRegisterHandler(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodPost{w.WriteHeader(http.StatusMethodNotAllowed);return};var in struct{Name string `json:"name"`;Password string `json:"password"`;ReferralCode string `json:"referral_code"`};if json.NewDecoder(r.Body).Decode(&in)!=nil||len(strings.TrimSpace(in.Password))<6{w.WriteHeader(http.StatusBadRequest);userJSON(w,map[string]any{"status":"error","message":"Name and password (minimum 6 characters) are required"});return};hash,err:=bcrypt.GenerateFromPassword([]byte(in.Password),bcrypt.DefaultCost);if err!=nil{w.WriteHeader(http.StatusInternalServerError);return};var refID *string;ref:=strings.TrimSpace(in.ReferralCode);if ref!=""{var id string;if err=userDB.QueryRow(`SELECT id::text FROM public.app_users WHERE referral_code=$1 AND status='active'`,ref).Scan(&id);err!=nil{w.WriteHeader(http.StatusBadRequest);userJSON(w,map[string]any{"status":"error","message":"Invalid referral code"});return};refID=&id};uid,err:=newPublicCode("LU",5);if err!=nil{w.WriteHeader(http.StatusInternalServerError);return};rcode,err:=newPublicCode("LU",4);if err!=nil{w.WriteHeader(http.StatusInternalServerError);return};var dbID string;if refID==nil{err=userDB.QueryRow(`INSERT INTO public.app_users(user_id,referral_code,password_hash,display_name) VALUES($1,$2,$3,$4) RETURNING id`,uid,rcode,string(hash),strings.TrimSpace(in.Name)).Scan(&dbID)}else{err=userDB.QueryRow(`INSERT INTO public.app_users(user_id,referral_code,password_hash,display_name,referred_by) VALUES($1,$2,$3,$4,$5::uuid) RETURNING id`,uid,rcode,string(hash),strings.TrimSpace(in.Name),*refID).Scan(&dbID)};if err!=nil{w.WriteHeader(http.StatusConflict);userJSON(w,map[string]any{"status":"error","message":"Registration failed or user already exists"});return};token,_:=newPortalToken();_,_=userDB.Exec(`INSERT INTO public.user_sessions_auth(user_id,token_hash,expires_at) VALUES($1::uuid,$2,$3)`,dbID,hashPortalToken(token),time.Now().UTC().Add(30*24*time.Hour));http.SetCookie(w,&http.Cookie{Name:"lumo_session",Value:token,Path:"/",HttpOnly:true,Secure:r.TLS!=nil,SameSite:http.SameSiteLaxMode,MaxAge:30*24*3600});userJSON(w,map[string]any{"status":"success","user_id":uid,"referral_code":rcode,"message":"Registration successful"})}
func userLoginHandler(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodPost{w.WriteHeader(http.StatusMethodNotAllowed);return};var in struct{UserID string `json:"user_id"`;Password string `json:"password"`};if json.NewDecoder(r.Body).Decode(&in)!=nil{w.WriteHeader(http.StatusBadRequest);return};var id,hash string;var name string;err:=userDB.QueryRow(`SELECT id::text,password_hash,display_name FROM public.app_users WHERE user_id=$1 AND status='active'`,strings.TrimSpace(in.UserID)).Scan(&id,&hash,&name);if err!=nil||bcrypt.CompareHashAndPassword([]byte(hash),[]byte(in.Password))!=nil{w.WriteHeader(http.StatusUnauthorized);userJSON(w,map[string]any{"status":"error","message":"Invalid User ID or password"});return};token,_:=newPortalToken();_,_=userDB.Exec(`INSERT INTO public.user_sessions_auth(user_id,token_hash,expires_at) VALUES($1::uuid,$2,$3)`,id,hashPortalToken(token),time.Now().UTC().Add(30*24*time.Hour));http.SetCookie(w,&http.Cookie{Name:"lumo_session",Value:token,Path:"/",HttpOnly:true,Secure:r.TLS!=nil,SameSite:http.SameSiteLaxMode,MaxAge:30*24*3600});userJSON(w,map[string]any{"status":"success","user_id":in.UserID,"name":name})}
func userLogoutHandler(w http.ResponseWriter,r *http.Request){token:=userPortalToken(r);if token!=""{_,_=userDB.Exec(`DELETE FROM public.user_sessions_auth WHERE token_hash=$1`,hashPortalToken(token))};http.SetCookie(w,&http.Cookie{Name:"lumo_session",Value:"",Path:"/",MaxAge:-1,HttpOnly:true});userJSON(w,map[string]any{"status":"success"})}
func userProfileHandler(w http.ResponseWriter,r *http.Request){uid,ok:=portalUser(r);if !ok{w.WriteHeader(http.StatusUnauthorized);userJSON(w,map[string]any{"status":"error","message":"Login required"});return};var id,name,rcode string;var balance,today,total float64;if err:=userDB.QueryRow(`SELECT id::text,display_name,referral_code,balance,today_earning,total_earning FROM public.app_users WHERE user_id=$1`,uid).Scan(&id,&name,&rcode,&balance,&today,&total);err!=nil{w.WriteHeader(http.StatusNotFound);return};var linked int;_=userDB.QueryRow(`SELECT count(*) FROM public.user_whatsapp_accounts WHERE user_id=$1::uuid AND status<>'removed'`,id).Scan(&linked);var sendsToday int64;_=userDB.QueryRow(`SELECT count(*) FROM public.task_claims WHERE user_id=$1::uuid AND status='sent' AND created_at>=date_trunc('day',now())`,id).Scan(&sendsToday);userJSON(w,map[string]any{"status":"success","user_id":uid,"name":name,"referral_code":rcode,"balance":balance,"today_earning":today,"total_earning":total,"linked_whatsapp":linked,"max_whatsapp":3,"today_send_total":sendsToday})}
func userPage(w http.ResponseWriter,r *http.Request,file string){if r.Method!=http.MethodGet{w.WriteHeader(http.StatusMethodNotAllowed);return};http.ServeFile(w,r,file)}
func init(){http.HandleFunc("/register",func(w http.ResponseWriter,r *http.Request){if r.Method==http.MethodGet{userPage(w,r,"user-register.html")}else{userRegisterHandler(w,r)}});http.HandleFunc("/login",func(w http.ResponseWriter,r *http.Request){if r.Method==http.MethodGet{userPage(w,r,"user-login.html")}else{userLoginHandler(w,r)}});http.HandleFunc("/logout",userLogoutHandler);http.HandleFunc("/api/user/profile",userProfileHandler);http.HandleFunc("/dashboard",func(w http.ResponseWriter,r *http.Request){userPage(w,r,"user-dashboard.html")})}
